# Generated by Django 4.1.3 on 2022-11-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Correo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emisor', models.CharField(max_length=50)),
                ('receptor', models.CharField(max_length=50)),
                ('departamento', models.IntegerField()),
                ('edificio', models.CharField(max_length=20, null=True)),
                ('fecha', models.DateField(default='2022-11-13')),
                ('Estado', models.CharField(choices=[('Entregado', 'Entregado'), ('En Conserjeria', 'En Conserjeria')], max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Residencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumDepEdificio', models.IntegerField()),
                ('Edificio', models.CharField(max_length=20, null=True)),
                ('Direccion', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
